Repository openshift/kubernetes-sigs-controller-tools, pull requests merged in 2019-03, with the labels that each got.

#3 🐛 Fix +required tag and update tests
  pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/toy_types.go
  pkg/internal/codegen/parse/crd.go
  pkg/internal/codegen/parse/util.go
Labels: lgtm, size/S

#4 [WIP] ✨ add nullable tag
  pkg/crd/generator/testData/config/crds/fun_v1alpha1_toy.yaml
  pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/toy_types.go
  pkg/internal/codegen/parse/crd.go
  pkg/internal/codegen/parse/util.go
Labels: do-not-merge/work-in-progress, lgtm, size/S

#5 Fix nullable
  pkg/internal/codegen/parse/crd.go
Labels: lgtm, size/M
